* About

  System of interconnected walipinis with aquaponics allows growing
  subtropical and tropical fruits indoors and loops water internally,
  allowing surviving the dry season with minimal water losses.

  Community through prosperity.

** Motivation

  Help 3M transition to the Cross of Sleeping Phoenix, do your work
  for mankind and the nature, while solving your own problems all at once.

** Objectives

  These are not why do I do it, but are sign-posts of success.

*** Personal

  - Providing shelter.
  - Food autonomy.
  - Water sufficiency even in the dry season.
  - Producing easily-tradeable items (fish, fruit).

*** Beyond

  - Promoting colaboration and hence safety in the community.
  - Being a valuable contributor is the Sleeping Phoenix's way of investment.
    By being valuable, people help you, protect you, take care of you.

* Energy
** Global transition
*** Cross of the Sleeping Phoenix

** Local significance
*** CDMX water issues

** My role in it

  # Mahadasha, progressed chart, D9.

*** History

  Patricia: do something with food/retiros
  Eden Project, but not realistic

* Overview
